/* Generated by Yosys 0.64 (git sha1 d8dab5b32666564eca8e18f412973853ce006e61, g++ 14.3.0-18 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/yosys_1775753385194/work=/usr/local/src/conda/yosys-0.64 -fdebug-prefix-map=/home/jahelwsl/miniconda3/envs/logic_design=/usr/local/src/conda-prefix -fPIC -O3) [conda-forge/yosys-feedstock] */

module c17(G1gat, G2gat, G3gat, G6gat, G7gat, G22gat, G23gat);
  input G1gat;
  wire G1gat;
  input G2gat;
  wire G2gat;
  input G3gat;
  wire G3gat;
  input G6gat;
  wire G6gat;
  input G7gat;
  wire G7gat;
  output G22gat;
  wire G22gat;
  output G23gat;
  wire G23gat;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  NAND2_X1 _4_ (
    .A1(G3gat),
    .A2(G6gat),
    .ZN(_2_)
  );
  NAND2_X1 _5_ (
    .A1(G2gat),
    .A2(_2_),
    .ZN(_3_)
  );
  NAND2_X1 _6_ (
    .A1(G7gat),
    .A2(_2_),
    .ZN(_0_)
  );
  NAND2_X1 _7_ (
    .A1(_3_),
    .A2(_0_),
    .ZN(G23gat)
  );
  NAND2_X1 _8_ (
    .A1(G3gat),
    .A2(G1gat),
    .ZN(_1_)
  );
  NAND2_X1 _9_ (
    .A1(_3_),
    .A2(_1_),
    .ZN(G22gat)
  );
endmodule
