import re
import argparse
import sys
import os

def extract_and_expand(verilog_text, decl_type):
    """
    Finds declarations (scalar and bus), expands buses, and returns a list of strings.
    Example: 'input [2:0] shamt;' becomes ['shamt_0', 'shamt_1', 'shamt_2']
    """
    expanded = []
    
    # 1. Find scalars: e.g., "input cin;"
    scalar_pattern = rf'^\s*{decl_type}\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*;'
    for match in re.finditer(scalar_pattern, verilog_text, re.MULTILINE):
        expanded.append(match.group(1))
        
    # 2. Find buses: e.g., "input [7:0] data_in;"
    bus_pattern = rf'^\s*{decl_type}\s+\[(\d+):(\d+)\]\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*;'
    for match in re.finditer(bus_pattern, verilog_text, re.MULTILINE):
        num1 = int(match.group(1))
        num2 = int(match.group(2))
        name = match.group(3)
        
        # Verilog buses can be [7:0] or [0:7], so we find the min and max safely
        start = min(num1, num2)
        end = max(num1, num2)
        
        for i in range(start, end + 1):
            expanded.append(f"{name}_{i}")
            
    return expanded

def sanitize_netlist(verilog_text):
    # --- Step 1: Remove Header ---
    verilog_text = re.sub(r'/\* Generated by Yosys.*?\*/\s*', '', verilog_text, flags=re.DOTALL)
    
    # --- Step 2: Convert Bus Accesses inside Gates ---
    # Changes shamt[2] to shamt_2 everywhere in the code
    verilog_text = re.sub(r'([a-zA-Z_][a-zA-Z0-9_]*)\[(\d+)\]', r'\1_\2', verilog_text)

    # --- Step 3: Extract & Expand Ports/Wires ---
    inputs = extract_and_expand(verilog_text, 'input')
    outputs = extract_and_expand(verilog_text, 'output')
    
    # Extract internal auto-generated wires (like _0_, _1_)
    internal_wires = re.findall(r'^\s*wire\s+(_\d+_)\s*;', verilog_text, re.MULTILINE)
    gates = re.findall(r'^\s*[a-zA-Z_][a-zA-Z0-9_]*\s+(_\d+_)\s*\(', verilog_text, re.MULTILINE)

    # --- Step 4: Map New Names for Auto-Generated IDs ---
    rename_map = {}
    renamed_internal_wires = []
    for i, w in enumerate(internal_wires, 1):
        new_name = f"n_{i}"
        rename_map[w] = new_name
        renamed_internal_wires.append(new_name)
        
    for i, g in enumerate(gates, 1):
        rename_map[g] = f"g{i}"

    # --- Step 5: Delete Old Declarations ---
    # Delete single-bit declarations
    verilog_text = re.sub(r'^\s*(input|output|wire)\s+[a-zA-Z_][a-zA-Z0-9_]*\s*;\n?', '', verilog_text, flags=re.MULTILINE)
    # Delete bus declarations
    verilog_text = re.sub(r'^\s*(input|output|wire)\s+\[\d+:\d+\]\s+[a-zA-Z_][a-zA-Z0-9_]*\s*;\n?', '', verilog_text, flags=re.MULTILINE)

    # --- Step 6: Build and Inject the Consolidated Block ---
    consolidated_io = ""
    if inputs:
        consolidated_io += f"  input {', '.join(inputs)};\n"
    if outputs:
        consolidated_io += f"  output {', '.join(outputs)};\n"
        
    all_wires = inputs + outputs + renamed_internal_wires
    if all_wires:
        consolidated_io += f"  wire {', '.join(all_wires)};\n"

    # Update the actual `module name(ports);` list to use the bit-blasted ports
    all_ports = inputs + outputs
    port_string = ", ".join(all_ports)
    
    verilog_text = re.sub(
        r'(^\s*module\s+[a-zA-Z_][a-zA-Z0-9_]*\s*)\([^)]*\)(\s*;)', 
        rf'\1({port_string})\2\n' + consolidated_io, 
        verilog_text, 
        count=1, 
        flags=re.MULTILINE
    )

    # --- Step 7: Apply the Renaming Map to Internal IDs ---
    def replacer(match):
        original_name = match.group(0)
        return rename_map.get(original_name, original_name)
    
    verilog_text = re.sub(r'_\d+_', replacer, verilog_text)
    
    # --- Step 8: Collapse Gate Instantiations to Single Line ---
    def collapse_replacer(match):
        indent = match.group(1)
        cell_type = match.group(2)
        inst_name = match.group(3)
        pins = match.group(4)
        
        # Ignore structural keywords to ensure we only collapse gate instantiations
        if cell_type in ['module', 'input', 'output', 'wire', 'assign']:
            return match.group(0)
            
        # Strip newlines and excess spaces from the pin mappings
        pins_single_line = re.sub(r'\s+', ' ', pins).strip()
        return f"{indent}{cell_type} {inst_name} ({pins_single_line});"
        
    # Matches: (indent) (cell_type) (instance_name) ( (pins) );
    gate_inst_pattern = re.compile(
        r'^(\s*)([a-zA-Z_][a-zA-Z0-9_]*)\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*\((.*?)\)\s*;', 
        re.MULTILINE | re.DOTALL
    )
    verilog_text = gate_inst_pattern.sub(collapse_replacer, verilog_text)

    # Final cleanup for excessive empty lines
    sanitized_text = re.sub(r'\n\s*\n', '\n', verilog_text)
    
    return sanitized_text, len(internal_wires), len(gates)

def main():
    parser = argparse.ArgumentParser(description="Sanitize, bit-blast, and format Yosys-generated Verilog netlists.")
    parser.add_argument('--input', required=True, help="Path to the input Yosys synthesized .v file")
    parser.add_argument('--output', required=True, help="Path where the sanitized .v file will be saved")
    args = parser.parse_args()

    if not os.path.isfile(args.input):
        print(f"Error: Input file '{args.input}' not found.")
        sys.exit(1)

    try:
        with open(args.input, 'r') as infile:
            verilog_text = infile.read()
    except Exception as e:
        print(f"Error reading {args.input}: {e}")
        sys.exit(1)

    print(f"Processing '{args.input}'...")
    clean_text, wire_count, gate_count = sanitize_netlist(verilog_text)

    try:
        with open(args.output, 'w') as outfile:
            outfile.write(clean_text)
        print(f"Success! Sanitized netlist saved to '{args.output}'.")
        print(f"Summary: Bit-blasted buses, collapsed gates. Renamed {wire_count} internal wires and {gate_count} gates.")
    except Exception as e:
        print(f"Error writing to {args.output}: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
