/* Generated by Yosys 0.64 (git sha1 d8dab5b32666564eca8e18f412973853ce006e61, g++ 14.3.0-18 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/yosys_1775753385194/work=/usr/local/src/conda/yosys-0.64 -fdebug-prefix-map=/home/jahelwsl/miniconda3/envs/logic_design=/usr/local/src/conda-prefix -fPIC -O3) [conda-forge/yosys-feedstock] */

module c432_CAC_k_10(G1GAT, G4GAT, G8GAT, G11GAT, G14GAT, G17GAT, G21GAT, G24GAT, G27GAT, G30GAT, G34GAT, G37GAT, G40GAT, G43GAT, G47GAT, G50GAT, G53GAT, G56GAT, G60GAT, G63GAT, G66GAT
, G69GAT, G73GAT, G76GAT, G79GAT, G82GAT, G86GAT, G89GAT, G92GAT, G95GAT, G99GAT, G102GAT, G105GAT, G108GAT, G112GAT, G115GAT, enc_in_0, enc_in_1, keyinput0, keyinput1, keyinput2, keyinput3
, keyinput4, keyinput5, keyinput6, keyinput7, keyinput8, keyinput9, G223GAT, G329GAT, G370GAT, G421GAT, G430GAT, G431GAT, G432GAT);
  input G1GAT;
  wire G1GAT;
  input G4GAT;
  wire G4GAT;
  input G8GAT;
  wire G8GAT;
  input G11GAT;
  wire G11GAT;
  input G14GAT;
  wire G14GAT;
  input G17GAT;
  wire G17GAT;
  input G21GAT;
  wire G21GAT;
  input G24GAT;
  wire G24GAT;
  input G27GAT;
  wire G27GAT;
  input G30GAT;
  wire G30GAT;
  input G34GAT;
  wire G34GAT;
  input G37GAT;
  wire G37GAT;
  input G40GAT;
  wire G40GAT;
  input G43GAT;
  wire G43GAT;
  input G47GAT;
  wire G47GAT;
  input G50GAT;
  wire G50GAT;
  input G53GAT;
  wire G53GAT;
  input G56GAT;
  wire G56GAT;
  input G60GAT;
  wire G60GAT;
  input G63GAT;
  wire G63GAT;
  input G66GAT;
  wire G66GAT;
  input G69GAT;
  wire G69GAT;
  input G73GAT;
  wire G73GAT;
  input G76GAT;
  wire G76GAT;
  input G79GAT;
  wire G79GAT;
  input G82GAT;
  wire G82GAT;
  input G86GAT;
  wire G86GAT;
  input G89GAT;
  wire G89GAT;
  input G92GAT;
  wire G92GAT;
  input G95GAT;
  wire G95GAT;
  input G99GAT;
  wire G99GAT;
  input G102GAT;
  wire G102GAT;
  input G105GAT;
  wire G105GAT;
  input G108GAT;
  wire G108GAT;
  input G112GAT;
  wire G112GAT;
  input G115GAT;
  wire G115GAT;
  input enc_in_0;
  wire enc_in_0;
  input enc_in_1;
  wire enc_in_1;
  input keyinput0;
  wire keyinput0;
  input keyinput1;
  wire keyinput1;
  input keyinput2;
  wire keyinput2;
  input keyinput3;
  wire keyinput3;
  input keyinput4;
  wire keyinput4;
  input keyinput5;
  wire keyinput5;
  input keyinput6;
  wire keyinput6;
  input keyinput7;
  wire keyinput7;
  input keyinput8;
  wire keyinput8;
  input keyinput9;
  wire keyinput9;
  output G223GAT;
  wire G223GAT;
  output G329GAT;
  wire G329GAT;
  output G370GAT;
  wire G370GAT;
  output G421GAT;
  wire G421GAT;
  output G430GAT;
  wire G430GAT;
  output G431GAT;
  wire G431GAT;
  output G432GAT;
  wire G432GAT;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire new_logic0;
  INV_X1 _128_ (
    .A(G66GAT),
    .ZN(_082_)
  );
  INV_X1 _129_ (
    .A(G21GAT),
    .ZN(_083_)
  );
  INV_X1 _130_ (
    .A(G8GAT),
    .ZN(_084_)
  );
  INV_X1 _131_ (
    .A(G1GAT),
    .ZN(_085_)
  );
  INV_X1 _132_ (
    .A(G24GAT),
    .ZN(_086_)
  );
  INV_X1 _133_ (
    .A(G27GAT),
    .ZN(_087_)
  );
  INV_X1 _134_ (
    .A(G17GAT),
    .ZN(_088_)
  );
  INV_X1 _135_ (
    .A(G63GAT),
    .ZN(_089_)
  );
  INV_X1 _136_ (
    .A(G95GAT),
    .ZN(_090_)
  );
  INV_X1 _137_ (
    .A(G43GAT),
    .ZN(_091_)
  );
  INV_X1 _138_ (
    .A(G82GAT),
    .ZN(_092_)
  );
  INV_X1 _139_ (
    .A(G108GAT),
    .ZN(_093_)
  );
  INV_X1 _140_ (
    .A(G56GAT),
    .ZN(_094_)
  );
  INV_X1 _141_ (
    .A(G99GAT),
    .ZN(_095_)
  );
  INV_X1 _142_ (
    .A(G112GAT),
    .ZN(_096_)
  );
  INV_X1 _143_ (
    .A(G47GAT),
    .ZN(_097_)
  );
  INV_X1 _144_ (
    .A(G73GAT),
    .ZN(_098_)
  );
  INV_X1 _145_ (
    .A(G60GAT),
    .ZN(_099_)
  );
  INV_X1 _146_ (
    .A(G105GAT),
    .ZN(_100_)
  );
  XOR2_X1 _147_ (
    .A(keyinput4),
    .B(G14GAT),
    .Z(_101_)
  );
  XOR2_X1 _148_ (
    .A(keyinput0),
    .B(G1GAT),
    .Z(_102_)
  );
  XNOR2_X1 _149_ (
    .A(keyinput1),
    .B(G4GAT),
    .ZN(_103_)
  );
  XNOR2_X1 _150_ (
    .A(G11GAT),
    .B(keyinput3),
    .ZN(_104_)
  );
  NOR2_X1 _151_ (
    .A1(_086_),
    .A2(keyinput7),
    .ZN(_105_)
  );
  XNOR2_X1 _152_ (
    .A(keyinput6),
    .B(G21GAT),
    .ZN(_106_)
  );
  NAND2_X1 _153_ (
    .A1(_087_),
    .A2(keyinput8),
    .ZN(_107_)
  );
  XOR2_X1 _154_ (
    .A(G17GAT),
    .B(keyinput5),
    .Z(_108_)
  );
  NOR2_X1 _155_ (
    .A1(_087_),
    .A2(keyinput8),
    .ZN(_109_)
  );
  NAND2_X1 _156_ (
    .A1(_086_),
    .A2(keyinput7),
    .ZN(_110_)
  );
  XNOR2_X1 _157_ (
    .A(keyinput2),
    .B(G8GAT),
    .ZN(_111_)
  );
  XNOR2_X1 _158_ (
    .A(keyinput9),
    .B(G30GAT),
    .ZN(_112_)
  );
  NAND4_X1 _159_ (
    .A1(_103_),
    .A2(_106_),
    .A3(_111_),
    .A4(_112_),
    .ZN(_113_)
  );
  OR4_X1 _160_ (
    .A1(_101_),
    .A2(_108_),
    .A3(_109_),
    .A4(_113_),
    .ZN(_114_)
  );
  NAND3_X1 _161_ (
    .A1(_104_),
    .A2(_107_),
    .A3(_110_),
    .ZN(_115_)
  );
  NOR4_X1 _162_ (
    .A1(_102_),
    .A2(_105_),
    .A3(_114_),
    .A4(_115_),
    .ZN(_116_)
  );
  NOR2_X1 _163_ (
    .A1(G37GAT),
    .A2(_091_),
    .ZN(_117_)
  );
  NOR2_X1 _164_ (
    .A1(G89GAT),
    .A2(_090_),
    .ZN(_118_)
  );
  NOR2_X1 _165_ (
    .A1(G102GAT),
    .A2(_093_),
    .ZN(_119_)
  );
  NAND2_X1 _166_ (
    .A1(_085_),
    .A2(G4GAT),
    .ZN(_120_)
  );
  NAND2_X1 _167_ (
    .A1(_089_),
    .A2(G69GAT),
    .ZN(_121_)
  );
  NAND2_X1 _168_ (
    .A1(_086_),
    .A2(G30GAT),
    .ZN(_122_)
  );
  NOR2_X1 _169_ (
    .A1(G50GAT),
    .A2(_094_),
    .ZN(_123_)
  );
  NOR2_X1 _170_ (
    .A1(G11GAT),
    .A2(_088_),
    .ZN(_124_)
  );
  NOR2_X1 _171_ (
    .A1(G76GAT),
    .A2(_092_),
    .ZN(_125_)
  );
  NAND3_X1 _172_ (
    .A1(_120_),
    .A2(_121_),
    .A3(_122_),
    .ZN(_126_)
  );
  OR4_X1 _173_ (
    .A1(_117_),
    .A2(_119_),
    .A3(_123_),
    .A4(_125_),
    .ZN(_127_)
  );
  NOR4_X1 _174_ (
    .A1(_118_),
    .A2(_124_),
    .A3(_126_),
    .A4(_127_),
    .ZN(_000_)
  );
  XNOR2_X1 _175_ (
    .A(_116_),
    .B(_000_),
    .ZN(_001_)
  );
  NOR4_X1 _176_ (
    .A1(G4GAT),
    .A2(G27GAT),
    .A3(G11GAT),
    .A4(G17GAT),
    .ZN(_002_)
  );
  NAND3_X1 _177_ (
    .A1(G8GAT),
    .A2(G1GAT),
    .A3(_002_),
    .ZN(_003_)
  );
  NOR4_X1 _178_ (
    .A1(G21GAT),
    .A2(G14GAT),
    .A3(_122_),
    .A4(_003_),
    .ZN(_004_)
  );
  OR2_X1 _179_ (
    .A1(_001_),
    .A2(_004_),
    .ZN(G223GAT)
  );
  NAND2_X1 _180_ (
    .A1(G37GAT),
    .A2(G223GAT),
    .ZN(_005_)
  );
  NAND2_X1 _181_ (
    .A1(G43GAT),
    .A2(_005_),
    .ZN(_006_)
  );
  NAND3_X1 _182_ (
    .A1(G43GAT),
    .A2(_097_),
    .A3(_005_),
    .ZN(_007_)
  );
  NAND2_X1 _183_ (
    .A1(G63GAT),
    .A2(G223GAT),
    .ZN(_008_)
  );
  NAND2_X1 _184_ (
    .A1(G69GAT),
    .A2(_008_),
    .ZN(_009_)
  );
  NAND3_X1 _185_ (
    .A1(G69GAT),
    .A2(_098_),
    .A3(_008_),
    .ZN(_010_)
  );
  NAND2_X1 _186_ (
    .A1(G50GAT),
    .A2(G223GAT),
    .ZN(_011_)
  );
  NAND3_X1 _187_ (
    .A1(G56GAT),
    .A2(_099_),
    .A3(_011_),
    .ZN(_012_)
  );
  AND2_X1 _188_ (
    .A1(G76GAT),
    .A2(G223GAT),
    .ZN(_013_)
  );
  NOR3_X1 _189_ (
    .A1(_092_),
    .A2(G86GAT),
    .A3(_013_),
    .ZN(_014_)
  );
  NAND2_X1 _190_ (
    .A1(G11GAT),
    .A2(_001_),
    .ZN(_015_)
  );
  NAND3_X1 _191_ (
    .A1(_083_),
    .A2(G17GAT),
    .A3(_015_),
    .ZN(_016_)
  );
  NAND2_X1 _192_ (
    .A1(G24GAT),
    .A2(_001_),
    .ZN(_017_)
  );
  NAND2_X1 _193_ (
    .A1(G30GAT),
    .A2(_017_),
    .ZN(_018_)
  );
  NOR2_X1 _194_ (
    .A1(G34GAT),
    .A2(_018_),
    .ZN(_019_)
  );
  NAND2_X1 _195_ (
    .A1(G1GAT),
    .A2(_001_),
    .ZN(_020_)
  );
  NAND2_X1 _196_ (
    .A1(G4GAT),
    .A2(_020_),
    .ZN(_021_)
  );
  NAND3_X1 _197_ (
    .A1(_084_),
    .A2(G4GAT),
    .A3(_020_),
    .ZN(_022_)
  );
  NAND2_X1 _198_ (
    .A1(_016_),
    .A2(_022_),
    .ZN(_023_)
  );
  NAND2_X1 _199_ (
    .A1(G102GAT),
    .A2(G223GAT),
    .ZN(_024_)
  );
  NAND2_X1 _200_ (
    .A1(G108GAT),
    .A2(_024_),
    .ZN(_025_)
  );
  AND3_X1 _201_ (
    .A1(G108GAT),
    .A2(_096_),
    .A3(_024_),
    .ZN(_026_)
  );
  NAND2_X1 _202_ (
    .A1(G89GAT),
    .A2(G223GAT),
    .ZN(_027_)
  );
  NAND3_X1 _203_ (
    .A1(G95GAT),
    .A2(_095_),
    .A3(_027_),
    .ZN(_028_)
  );
  NAND4_X1 _204_ (
    .A1(_007_),
    .A2(_010_),
    .A3(_012_),
    .A4(_028_),
    .ZN(_029_)
  );
  OR4_X1 _205_ (
    .A1(_014_),
    .A2(_019_),
    .A3(_023_),
    .A4(_026_),
    .ZN(_030_)
  );
  OR2_X1 _206_ (
    .A1(_029_),
    .A2(_030_),
    .ZN(G329GAT)
  );
  AND2_X1 _207_ (
    .A1(G8GAT),
    .A2(G329GAT),
    .ZN(_031_)
  );
  NOR3_X1 _208_ (
    .A1(G14GAT),
    .A2(_021_),
    .A3(_031_),
    .ZN(_032_)
  );
  NAND2_X1 _209_ (
    .A1(G99GAT),
    .A2(G329GAT),
    .ZN(_033_)
  );
  AND3_X1 _210_ (
    .A1(G95GAT),
    .A2(_027_),
    .A3(_033_),
    .ZN(_034_)
  );
  AND4_X1 _211_ (
    .A1(G95GAT),
    .A2(_100_),
    .A3(_027_),
    .A4(_033_),
    .ZN(_035_)
  );
  NAND2_X1 _212_ (
    .A1(G60GAT),
    .A2(G329GAT),
    .ZN(_036_)
  );
  NAND3_X1 _213_ (
    .A1(G56GAT),
    .A2(_011_),
    .A3(_036_),
    .ZN(_037_)
  );
  NAND4_X1 _214_ (
    .A1(_082_),
    .A2(G56GAT),
    .A3(_011_),
    .A4(_036_),
    .ZN(_038_)
  );
  AND2_X1 _215_ (
    .A1(G47GAT),
    .A2(G329GAT),
    .ZN(_039_)
  );
  NOR3_X1 _216_ (
    .A1(G53GAT),
    .A2(_006_),
    .A3(_039_),
    .ZN(_040_)
  );
  AND2_X1 _217_ (
    .A1(G73GAT),
    .A2(G329GAT),
    .ZN(_041_)
  );
  NOR2_X1 _218_ (
    .A1(_009_),
    .A2(_041_),
    .ZN(_042_)
  );
  NOR3_X1 _219_ (
    .A1(G79GAT),
    .A2(_009_),
    .A3(_041_),
    .ZN(_043_)
  );
  AND2_X1 _220_ (
    .A1(G34GAT),
    .A2(G329GAT),
    .ZN(_044_)
  );
  NOR3_X1 _221_ (
    .A1(G40GAT),
    .A2(_018_),
    .A3(_044_),
    .ZN(_045_)
  );
  AND2_X1 _222_ (
    .A1(G112GAT),
    .A2(G329GAT),
    .ZN(_046_)
  );
  NOR3_X1 _223_ (
    .A1(G115GAT),
    .A2(_025_),
    .A3(_046_),
    .ZN(_047_)
  );
  NOR4_X1 _224_ (
    .A1(_092_),
    .A2(_013_),
    .A3(_029_),
    .A4(_030_),
    .ZN(_048_)
  );
  NOR2_X1 _225_ (
    .A1(_014_),
    .A2(_048_),
    .ZN(_049_)
  );
  OR2_X1 _226_ (
    .A1(G92GAT),
    .A2(_049_),
    .ZN(_050_)
  );
  NAND2_X1 _227_ (
    .A1(G21GAT),
    .A2(G329GAT),
    .ZN(_051_)
  );
  AND3_X1 _228_ (
    .A1(G17GAT),
    .A2(_015_),
    .A3(_051_),
    .ZN(_052_)
  );
  NAND2_X1 _229_ (
    .A1(_087_),
    .A2(_052_),
    .ZN(_053_)
  );
  AND2_X1 _230_ (
    .A1(_038_),
    .A2(_050_),
    .ZN(_054_)
  );
  NOR4_X1 _231_ (
    .A1(_032_),
    .A2(_040_),
    .A3(_043_),
    .A4(_045_),
    .ZN(_055_)
  );
  NOR2_X1 _232_ (
    .A1(_035_),
    .A2(_047_),
    .ZN(_056_)
  );
  NAND4_X1 _233_ (
    .A1(_053_),
    .A2(_054_),
    .A3(_055_),
    .A4(_056_),
    .ZN(G370GAT)
  );
  AND2_X1 _234_ (
    .A1(G40GAT),
    .A2(G370GAT),
    .ZN(_057_)
  );
  OR3_X1 _235_ (
    .A1(_018_),
    .A2(_044_),
    .A3(_057_),
    .ZN(_058_)
  );
  NAND2_X1 _236_ (
    .A1(G105GAT),
    .A2(G370GAT),
    .ZN(_059_)
  );
  AND2_X1 _237_ (
    .A1(_034_),
    .A2(_059_),
    .ZN(_060_)
  );
  OR2_X1 _238_ (
    .A1(_049_),
    .A2(G370GAT),
    .ZN(_061_)
  );
  AND2_X1 _239_ (
    .A1(_050_),
    .A2(_061_),
    .ZN(_062_)
  );
  NAND4_X1 _240_ (
    .A1(_034_),
    .A2(_050_),
    .A3(_059_),
    .A4(_061_),
    .ZN(_063_)
  );
  NAND2_X1 _241_ (
    .A1(G79GAT),
    .A2(G370GAT),
    .ZN(_064_)
  );
  NAND2_X1 _242_ (
    .A1(_042_),
    .A2(_064_),
    .ZN(_065_)
  );
  NAND3_X1 _243_ (
    .A1(_037_),
    .A2(_042_),
    .A3(_064_),
    .ZN(_066_)
  );
  NAND2_X1 _244_ (
    .A1(G66GAT),
    .A2(_043_),
    .ZN(_067_)
  );
  AND2_X1 _245_ (
    .A1(G53GAT),
    .A2(G370GAT),
    .ZN(_068_)
  );
  OR3_X1 _246_ (
    .A1(_006_),
    .A2(_039_),
    .A3(_068_),
    .ZN(_069_)
  );
  NAND4_X1 _247_ (
    .A1(_063_),
    .A2(_066_),
    .A3(_067_),
    .A4(_069_),
    .ZN(_070_)
  );
  NAND2_X1 _248_ (
    .A1(_058_),
    .A2(_070_),
    .ZN(_071_)
  );
  NAND2_X1 _249_ (
    .A1(G27GAT),
    .A2(G370GAT),
    .ZN(_072_)
  );
  NAND2_X1 _250_ (
    .A1(_052_),
    .A2(_072_),
    .ZN(_073_)
  );
  NAND2_X1 _251_ (
    .A1(_071_),
    .A2(_073_),
    .ZN(G432GAT)
  );
  AND2_X1 _252_ (
    .A1(G66GAT),
    .A2(G370GAT),
    .ZN(_074_)
  );
  OR2_X1 _253_ (
    .A1(_037_),
    .A2(_074_),
    .ZN(_075_)
  );
  NAND2_X1 _254_ (
    .A1(_062_),
    .A2(_065_),
    .ZN(_076_)
  );
  NAND3_X1 _255_ (
    .A1(_069_),
    .A2(_075_),
    .A3(_076_),
    .ZN(_077_)
  );
  NAND3_X1 _256_ (
    .A1(_058_),
    .A2(_073_),
    .A3(_077_),
    .ZN(G431GAT)
  );
  NAND4_X1 _257_ (
    .A1(_058_),
    .A2(_069_),
    .A3(_073_),
    .A4(_075_),
    .ZN(G430GAT)
  );
  NAND2_X1 _258_ (
    .A1(_025_),
    .A2(_062_),
    .ZN(_078_)
  );
  NOR4_X1 _259_ (
    .A1(_042_),
    .A2(_060_),
    .A3(G430GAT),
    .A4(_078_),
    .ZN(_079_)
  );
  AND2_X1 _260_ (
    .A1(G14GAT),
    .A2(G370GAT),
    .ZN(_080_)
  );
  NOR3_X1 _261_ (
    .A1(_021_),
    .A2(_031_),
    .A3(_080_),
    .ZN(_081_)
  );
  NOR2_X1 _262_ (
    .A1(_079_),
    .A2(_081_),
    .ZN(G421GAT)
  );
  assign new_logic0 = 1'h0;
endmodule
