/* Generated by Yosys 0.64 (git sha1 d8dab5b32666564eca8e18f412973853ce006e61, g++ 14.3.0-18 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/yosys_1775753385194/work=/usr/local/src/conda/yosys-0.64 -fdebug-prefix-map=/home/jahelwsl/miniconda3/envs/logic_design=/usr/local/src/conda-prefix -fPIC -O3) [conda-forge/yosys-feedstock] */

module c432(G1GAT, G4GAT, G8GAT, G11GAT, G14GAT, G17GAT, G21GAT, G24GAT, G27GAT, G30GAT, G34GAT, G37GAT, G40GAT, G43GAT, G47GAT, G50GAT, G53GAT, G56GAT, G60GAT, G63GAT, G66GAT
, G69GAT, G73GAT, G76GAT, G79GAT, G82GAT, G86GAT, G89GAT, G92GAT, G95GAT, G99GAT, G102GAT, G105GAT, G108GAT, G112GAT, G115GAT, enc_in_0, enc_in_1, G223GAT, G329GAT, G370GAT, G421GAT
, G430GAT, G431GAT, G432GAT);
  input G1GAT;
  wire G1GAT;
  input G4GAT;
  wire G4GAT;
  input G8GAT;
  wire G8GAT;
  input G11GAT;
  wire G11GAT;
  input G14GAT;
  wire G14GAT;
  input G17GAT;
  wire G17GAT;
  input G21GAT;
  wire G21GAT;
  input G24GAT;
  wire G24GAT;
  input G27GAT;
  wire G27GAT;
  input G30GAT;
  wire G30GAT;
  input G34GAT;
  wire G34GAT;
  input G37GAT;
  wire G37GAT;
  input G40GAT;
  wire G40GAT;
  input G43GAT;
  wire G43GAT;
  input G47GAT;
  wire G47GAT;
  input G50GAT;
  wire G50GAT;
  input G53GAT;
  wire G53GAT;
  input G56GAT;
  wire G56GAT;
  input G60GAT;
  wire G60GAT;
  input G63GAT;
  wire G63GAT;
  input G66GAT;
  wire G66GAT;
  input G69GAT;
  wire G69GAT;
  input G73GAT;
  wire G73GAT;
  input G76GAT;
  wire G76GAT;
  input G79GAT;
  wire G79GAT;
  input G82GAT;
  wire G82GAT;
  input G86GAT;
  wire G86GAT;
  input G89GAT;
  wire G89GAT;
  input G92GAT;
  wire G92GAT;
  input G95GAT;
  wire G95GAT;
  input G99GAT;
  wire G99GAT;
  input G102GAT;
  wire G102GAT;
  input G105GAT;
  wire G105GAT;
  input G108GAT;
  wire G108GAT;
  input G112GAT;
  wire G112GAT;
  input G115GAT;
  wire G115GAT;
  input enc_in_0;
  wire enc_in_0;
  input enc_in_1;
  wire enc_in_1;
  output G223GAT;
  wire G223GAT;
  output G329GAT;
  wire G329GAT;
  output G370GAT;
  wire G370GAT;
  output G421GAT;
  wire G421GAT;
  output G430GAT;
  wire G430GAT;
  output G431GAT;
  wire G431GAT;
  output G432GAT;
  wire G432GAT;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  INV_X1 _117_ (
    .A(G66GAT),
    .ZN(_062_)
  );
  INV_X1 _118_ (
    .A(G11GAT),
    .ZN(_063_)
  );
  INV_X1 _119_ (
    .A(G69GAT),
    .ZN(_064_)
  );
  INV_X1 _120_ (
    .A(G56GAT),
    .ZN(_065_)
  );
  INV_X1 _121_ (
    .A(G43GAT),
    .ZN(_066_)
  );
  INV_X1 _122_ (
    .A(G4GAT),
    .ZN(_067_)
  );
  INV_X1 _123_ (
    .A(G76GAT),
    .ZN(_068_)
  );
  INV_X1 _124_ (
    .A(G95GAT),
    .ZN(_069_)
  );
  INV_X1 _125_ (
    .A(G108GAT),
    .ZN(_070_)
  );
  INV_X1 _126_ (
    .A(G30GAT),
    .ZN(_071_)
  );
  INV_X1 _127_ (
    .A(G112GAT),
    .ZN(_072_)
  );
  INV_X1 _128_ (
    .A(G34GAT),
    .ZN(_073_)
  );
  INV_X1 _129_ (
    .A(G73GAT),
    .ZN(_074_)
  );
  INV_X1 _130_ (
    .A(G47GAT),
    .ZN(_075_)
  );
  INV_X1 _131_ (
    .A(G60GAT),
    .ZN(_076_)
  );
  INV_X1 _132_ (
    .A(G21GAT),
    .ZN(_077_)
  );
  INV_X1 _133_ (
    .A(G8GAT),
    .ZN(_078_)
  );
  INV_X1 _134_ (
    .A(G86GAT),
    .ZN(_079_)
  );
  INV_X1 _135_ (
    .A(G40GAT),
    .ZN(_080_)
  );
  INV_X1 _136_ (
    .A(G27GAT),
    .ZN(_081_)
  );
  INV_X1 _137_ (
    .A(G105GAT),
    .ZN(_082_)
  );
  INV_X1 _138_ (
    .A(G92GAT),
    .ZN(_083_)
  );
  INV_X1 _139_ (
    .A(G79GAT),
    .ZN(_084_)
  );
  NAND2_X1 _140_ (
    .A1(_063_),
    .A2(G17GAT),
    .ZN(_085_)
  );
  NOR2_X1 _141_ (
    .A1(G37GAT),
    .A2(_066_),
    .ZN(_086_)
  );
  NOR2_X1 _142_ (
    .A1(G63GAT),
    .A2(_064_),
    .ZN(_087_)
  );
  NOR2_X1 _143_ (
    .A1(G102GAT),
    .A2(_070_),
    .ZN(_088_)
  );
  NOR2_X1 _144_ (
    .A1(G89GAT),
    .A2(_069_),
    .ZN(_089_)
  );
  NAND2_X1 _145_ (
    .A1(_068_),
    .A2(G82GAT),
    .ZN(_090_)
  );
  NOR2_X1 _146_ (
    .A1(G1GAT),
    .A2(_067_),
    .ZN(_091_)
  );
  NOR2_X1 _147_ (
    .A1(G24GAT),
    .A2(_071_),
    .ZN(_092_)
  );
  NOR2_X1 _148_ (
    .A1(G50GAT),
    .A2(_065_),
    .ZN(_093_)
  );
  NOR3_X1 _149_ (
    .A1(_086_),
    .A2(_091_),
    .A3(_092_),
    .ZN(_094_)
  );
  NOR4_X1 _150_ (
    .A1(_087_),
    .A2(_088_),
    .A3(_089_),
    .A4(_093_),
    .ZN(_095_)
  );
  NAND4_X1 _151_ (
    .A1(_085_),
    .A2(_090_),
    .A3(_094_),
    .A4(_095_),
    .ZN(G223GAT)
  );
  NAND2_X1 _152_ (
    .A1(G11GAT),
    .A2(G223GAT),
    .ZN(_096_)
  );
  NAND3_X1 _153_ (
    .A1(G17GAT),
    .A2(_077_),
    .A3(_096_),
    .ZN(_097_)
  );
  NAND2_X1 _154_ (
    .A1(G63GAT),
    .A2(G223GAT),
    .ZN(_098_)
  );
  NAND3_X1 _155_ (
    .A1(G69GAT),
    .A2(_074_),
    .A3(_098_),
    .ZN(_099_)
  );
  NAND2_X1 _156_ (
    .A1(G1GAT),
    .A2(G223GAT),
    .ZN(_100_)
  );
  NAND2_X1 _157_ (
    .A1(G4GAT),
    .A2(_100_),
    .ZN(_101_)
  );
  NAND3_X1 _158_ (
    .A1(G4GAT),
    .A2(_078_),
    .A3(_100_),
    .ZN(_102_)
  );
  NAND2_X1 _159_ (
    .A1(G89GAT),
    .A2(G223GAT),
    .ZN(_103_)
  );
  NAND2_X1 _160_ (
    .A1(G95GAT),
    .A2(_103_),
    .ZN(_104_)
  );
  NOR2_X1 _161_ (
    .A1(G99GAT),
    .A2(_104_),
    .ZN(_105_)
  );
  NAND2_X1 _162_ (
    .A1(G76GAT),
    .A2(G223GAT),
    .ZN(_106_)
  );
  NAND3_X1 _163_ (
    .A1(G82GAT),
    .A2(_079_),
    .A3(_106_),
    .ZN(_107_)
  );
  NAND2_X1 _164_ (
    .A1(G24GAT),
    .A2(G223GAT),
    .ZN(_108_)
  );
  NAND3_X1 _165_ (
    .A1(G30GAT),
    .A2(_073_),
    .A3(_108_),
    .ZN(_109_)
  );
  NAND2_X1 _166_ (
    .A1(G50GAT),
    .A2(G223GAT),
    .ZN(_110_)
  );
  NAND3_X1 _167_ (
    .A1(G56GAT),
    .A2(_076_),
    .A3(_110_),
    .ZN(_111_)
  );
  NAND2_X1 _168_ (
    .A1(G102GAT),
    .A2(G223GAT),
    .ZN(_112_)
  );
  NAND2_X1 _169_ (
    .A1(G108GAT),
    .A2(_112_),
    .ZN(_113_)
  );
  NAND3_X1 _170_ (
    .A1(G108GAT),
    .A2(_072_),
    .A3(_112_),
    .ZN(_114_)
  );
  NAND2_X1 _171_ (
    .A1(G37GAT),
    .A2(G223GAT),
    .ZN(_115_)
  );
  NAND3_X1 _172_ (
    .A1(G43GAT),
    .A2(_075_),
    .A3(_115_),
    .ZN(_116_)
  );
  NAND4_X1 _173_ (
    .A1(_097_),
    .A2(_099_),
    .A3(_114_),
    .A4(_116_),
    .ZN(_000_)
  );
  NAND4_X1 _174_ (
    .A1(_102_),
    .A2(_107_),
    .A3(_109_),
    .A4(_111_),
    .ZN(_001_)
  );
  OR3_X1 _175_ (
    .A1(_105_),
    .A2(_000_),
    .A3(_001_),
    .ZN(G329GAT)
  );
  NAND2_X1 _176_ (
    .A1(G60GAT),
    .A2(G329GAT),
    .ZN(_002_)
  );
  NAND3_X1 _177_ (
    .A1(G56GAT),
    .A2(_110_),
    .A3(_002_),
    .ZN(_003_)
  );
  NAND4_X1 _178_ (
    .A1(_062_),
    .A2(G56GAT),
    .A3(_110_),
    .A4(_002_),
    .ZN(_004_)
  );
  NAND3_X1 _179_ (
    .A1(G17GAT),
    .A2(_081_),
    .A3(_096_),
    .ZN(_005_)
  );
  OR2_X1 _180_ (
    .A1(G14GAT),
    .A2(_101_),
    .ZN(_006_)
  );
  OR2_X1 _181_ (
    .A1(G115GAT),
    .A2(_113_),
    .ZN(_007_)
  );
  NAND3_X1 _182_ (
    .A1(G30GAT),
    .A2(_080_),
    .A3(_108_),
    .ZN(_008_)
  );
  NOR2_X1 _183_ (
    .A1(G105GAT),
    .A2(_104_),
    .ZN(_009_)
  );
  NAND4_X1 _184_ (
    .A1(_005_),
    .A2(_006_),
    .A3(_007_),
    .A4(_008_),
    .ZN(_010_)
  );
  NOR2_X1 _185_ (
    .A1(_009_),
    .A2(_010_),
    .ZN(_011_)
  );
  OR2_X1 _186_ (
    .A1(G329GAT),
    .A2(_011_),
    .ZN(_012_)
  );
  NOR2_X1 _187_ (
    .A1(G27GAT),
    .A2(_097_),
    .ZN(_013_)
  );
  NAND2_X1 _188_ (
    .A1(_082_),
    .A2(_105_),
    .ZN(_014_)
  );
  NOR2_X1 _189_ (
    .A1(G115GAT),
    .A2(_114_),
    .ZN(_015_)
  );
  NOR2_X1 _190_ (
    .A1(G34GAT),
    .A2(_008_),
    .ZN(_016_)
  );
  NOR2_X1 _191_ (
    .A1(G14GAT),
    .A2(_102_),
    .ZN(_017_)
  );
  NOR4_X1 _192_ (
    .A1(_013_),
    .A2(_015_),
    .A3(_016_),
    .A4(_017_),
    .ZN(_018_)
  );
  NAND4_X1 _193_ (
    .A1(_004_),
    .A2(_012_),
    .A3(_014_),
    .A4(_018_),
    .ZN(_019_)
  );
  NAND2_X1 _194_ (
    .A1(G47GAT),
    .A2(G329GAT),
    .ZN(_020_)
  );
  NAND3_X1 _195_ (
    .A1(G43GAT),
    .A2(_115_),
    .A3(_020_),
    .ZN(_021_)
  );
  NOR2_X1 _196_ (
    .A1(G53GAT),
    .A2(_021_),
    .ZN(_022_)
  );
  NAND2_X1 _197_ (
    .A1(G86GAT),
    .A2(G329GAT),
    .ZN(_023_)
  );
  AND3_X1 _198_ (
    .A1(G82GAT),
    .A2(_106_),
    .A3(_023_),
    .ZN(_024_)
  );
  INV_X1 _199_ (
    .A(_024_),
    .ZN(_025_)
  );
  AND2_X1 _200_ (
    .A1(_083_),
    .A2(_024_),
    .ZN(_026_)
  );
  INV_X1 _201_ (
    .A(_026_),
    .ZN(_027_)
  );
  NAND2_X1 _202_ (
    .A1(G73GAT),
    .A2(G329GAT),
    .ZN(_028_)
  );
  AND3_X1 _203_ (
    .A1(G69GAT),
    .A2(_098_),
    .A3(_028_),
    .ZN(_029_)
  );
  AND2_X1 _204_ (
    .A1(_084_),
    .A2(_029_),
    .ZN(_030_)
  );
  OR4_X1 _205_ (
    .A1(_019_),
    .A2(_022_),
    .A3(_026_),
    .A4(_030_),
    .ZN(G370GAT)
  );
  NAND2_X1 _206_ (
    .A1(G27GAT),
    .A2(G370GAT),
    .ZN(_031_)
  );
  NAND2_X1 _207_ (
    .A1(G21GAT),
    .A2(G329GAT),
    .ZN(_032_)
  );
  NAND4_X1 _208_ (
    .A1(G17GAT),
    .A2(_096_),
    .A3(_031_),
    .A4(_032_),
    .ZN(_033_)
  );
  NAND2_X1 _209_ (
    .A1(G40GAT),
    .A2(G370GAT),
    .ZN(_034_)
  );
  NAND2_X1 _210_ (
    .A1(G34GAT),
    .A2(G329GAT),
    .ZN(_035_)
  );
  AND4_X1 _211_ (
    .A1(G30GAT),
    .A2(_108_),
    .A3(_034_),
    .A4(_035_),
    .ZN(_036_)
  );
  NAND4_X1 _212_ (
    .A1(G30GAT),
    .A2(_108_),
    .A3(_034_),
    .A4(_035_),
    .ZN(_037_)
  );
  NAND2_X1 _213_ (
    .A1(G79GAT),
    .A2(G370GAT),
    .ZN(_038_)
  );
  NAND2_X1 _214_ (
    .A1(_029_),
    .A2(_038_),
    .ZN(_039_)
  );
  NAND3_X1 _215_ (
    .A1(_003_),
    .A2(_029_),
    .A3(_038_),
    .ZN(_040_)
  );
  NAND2_X1 _216_ (
    .A1(G105GAT),
    .A2(G370GAT),
    .ZN(_041_)
  );
  AND2_X1 _217_ (
    .A1(G99GAT),
    .A2(G329GAT),
    .ZN(_042_)
  );
  NOR2_X1 _218_ (
    .A1(_104_),
    .A2(_042_),
    .ZN(_043_)
  );
  AND2_X1 _219_ (
    .A1(_041_),
    .A2(_043_),
    .ZN(_044_)
  );
  OR2_X1 _220_ (
    .A1(_025_),
    .A2(G370GAT),
    .ZN(_045_)
  );
  AND2_X1 _221_ (
    .A1(_027_),
    .A2(_045_),
    .ZN(_046_)
  );
  NAND4_X1 _222_ (
    .A1(_027_),
    .A2(_041_),
    .A3(_043_),
    .A4(_045_),
    .ZN(_047_)
  );
  NAND2_X1 _223_ (
    .A1(G66GAT),
    .A2(_030_),
    .ZN(_048_)
  );
  NOR2_X1 _224_ (
    .A1(_021_),
    .A2(G370GAT),
    .ZN(_049_)
  );
  NOR2_X1 _225_ (
    .A1(_022_),
    .A2(_049_),
    .ZN(_050_)
  );
  AND4_X1 _226_ (
    .A1(_040_),
    .A2(_047_),
    .A3(_048_),
    .A4(_050_),
    .ZN(_051_)
  );
  OR2_X1 _227_ (
    .A1(_036_),
    .A2(_051_),
    .ZN(_052_)
  );
  NAND2_X1 _228_ (
    .A1(_033_),
    .A2(_052_),
    .ZN(G432GAT)
  );
  AND2_X1 _229_ (
    .A1(G66GAT),
    .A2(G370GAT),
    .ZN(_053_)
  );
  OR2_X1 _230_ (
    .A1(_003_),
    .A2(_053_),
    .ZN(_054_)
  );
  NAND2_X1 _231_ (
    .A1(_039_),
    .A2(_046_),
    .ZN(_055_)
  );
  NAND3_X1 _232_ (
    .A1(_050_),
    .A2(_054_),
    .A3(_055_),
    .ZN(_056_)
  );
  NAND3_X1 _233_ (
    .A1(_033_),
    .A2(_037_),
    .A3(_056_),
    .ZN(G431GAT)
  );
  NAND4_X1 _234_ (
    .A1(_033_),
    .A2(_037_),
    .A3(_050_),
    .A4(_054_),
    .ZN(G430GAT)
  );
  NAND2_X1 _235_ (
    .A1(_113_),
    .A2(_046_),
    .ZN(_057_)
  );
  NOR4_X1 _236_ (
    .A1(_029_),
    .A2(_044_),
    .A3(G430GAT),
    .A4(_057_),
    .ZN(_058_)
  );
  AND2_X1 _237_ (
    .A1(G14GAT),
    .A2(G370GAT),
    .ZN(_059_)
  );
  AND2_X1 _238_ (
    .A1(G8GAT),
    .A2(G329GAT),
    .ZN(_060_)
  );
  NOR3_X1 _239_ (
    .A1(_101_),
    .A2(_059_),
    .A3(_060_),
    .ZN(_061_)
  );
  NOR2_X1 _240_ (
    .A1(_058_),
    .A2(_061_),
    .ZN(G421GAT)
  );
endmodule
